jupyterhub:
  singleuser:
    storage:
      type: none
    cloudMetadata:
      blockWithIptables: false
  rbac:
    enabled: false
  prePuller:
    hook:
      enabled: false
    continuous:
      enabled: false
  proxy:
    service:
      type: ClusterIP
  scheduling:
    userScheduler:
      enabled: false
    corePods:
      tolerations: []
    userPods:
      tolerations: []
